
server:
  port:
    0

spring:
  application:
    name: catalog-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/testdb
    username: sa
    password: 1234
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome